### ISSUE TITLE
Crash on failure to login user on backend

### ISSUE THREAD

**Issue by Jef-Malfliet** [MoutPessemier/GameHub-Android#1]
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.

The changes made to the UI must be done in a RunWithUI block when the app reaches the catch-block in the OnSucces method in LoginActivity.

**Comment by MoutPessemier** [comment]
You're right, changes are made. Thanks!

**Comment by Jef-Malfliet** [comment]
😘
